spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
      # host: ${REDIS_HOST}
      # port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD}
      # ssl:
      #   enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: url-shortener-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.urlshortener.*"

server:
  port: ${PORT:8080}

app:
  base-url: ${APP_BASE_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.urlshortener: INFO
    org.springframework: WARN